### PR TITLE
Conda patch for None vs empty string change

### PR DESCRIPTION
**Pull request by sarnold**
So much (global) Python churn I have no idea why this changed; actually I was hoping you had an answer for that...  Anyway, I dropped a patch for the conda recipe just in case. I haven't seen this issue crop up in conda-forge at all, so, go figure...

### CODE REVIEW

**Comment by sarnold** [comment]
Hmm, I was busy the other day so I only tested the conda build, but now I'm seeing the same breakage (change) when running the usual tox environments in my local checkout; applying the patch makes everything green again.  That said, it's not clear at all what the actual root cause is.  Also it appears the conda patch isn't just for conda now...

**Comment by sarnold** [comment]
Successfully installed pyre2-0.3.6 regex-2021.8.28
perf run-test: commands[2] | python tests/performance.py

```
+-----------------+---------------------------------------------------------------------------+------------+--------------+---------------+-------------+-----------------+----------------+
|Test             |Description                                                                |# total runs|``re`` time(s)|``re2`` time(s)|% ``re`` time|``regex`` time(s)|% ``regex`` time|
+=================+===========================================================================+============+==============+===============+=============+=================+================+
|Findall URI|Email|Find list of '([a-zA-Z][a-zA-Z0-9]*)://([^ /]+)(/[^ ]*)?|([^ @]+)@([^ @]+)'|2           |12.558        |0.065          |0.51%        |9.968            |0.65%           |
+-----------------+---------------------------------------------------------------------------+------------+--------------+---------------+-------------+-----------------+----------------+
|Replace WikiLinks|This test replaces links of the form [[Obama|Barack_Obama]] to Obama.      |100         |1.093         |1.342          |122.78%      |1.525            |88.00%          |
+-----------------+---------------------------------------------------------------------------+------------+--------------+---------------+-------------+-----------------+----------------+
|Remove WikiLinks |This test splits the data by the <page> tag.                               |100         |0.655         |0.310          |47.23%       |0.635            |48.74%          |
+-----------------+---------------------------------------------------------------------------+------------+--------------+---------------+-------------+-----------------+----------------+
```

**Comment by andreasvc** [comment]
Hmm. I get the following with Python 3.7:
```
031 This one was formerly a None vs empty string difference until July 2021:
032
033     >>> re.search(r'((.*)*.)', 'a').groups()
034     ('a', '')
035     >>> re2.search(r'((.*)*.)', 'a').groups()
Expected:
    ('a', '')
Got:
    ('a', None)
```
Could it be that the behavior changed in Python 3.8+? Perhaps taking the test out is best if Python's behavior is inconsistent.

**Comment by andreasvc** [comment]
This seems to be related to #27

**Pull request merged**
